# Generated by Django 3.1.2 on 2021-01-15 07:59

import SocialApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='image',
            field=models.ImageField(upload_to=SocialApp.models.uploads),
        ),
        migrations.AlterField(
            model_name='socialissue',
            name='image',
            field=models.ImageField(upload_to=SocialApp.models.uploads),
        ),
        migrations.AlterField(
            model_name='socialissue',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
