# Generated by Django 3.1.4 on 2021-02-04 09:20

import SocialApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_auto_20210202_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspost',
            old_name='title',
            new_name='campaign_title',
        ),
        migrations.RenameField(
            model_name='socialissue',
            old_name='title',
            new_name='campaign_title',
        ),
        migrations.RemoveField(
            model_name='businesspost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='socialissue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='socialissue',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='socialissue',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='socialissue',
            name='upvote',
        ),
        migrations.AddField(
            model_name='businesspost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialissue',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to=SocialApp.models.uploads, width_field=50),
        ),
        migrations.AlterField(
            model_name='socialissue',
            name='image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to=SocialApp.models.uploads, width_field=50),
        ),
    ]
