# Generated by Django 3.1.4 on 2021-02-09 05:06

import SocialApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0006_auto_20210209_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='businesspost',
            name='image',
            field=models.ImageField(upload_to=SocialApp.models.uploads),
        ),
    ]
