# Generated by Django 3.1.4 on 2021-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0008_auto_20210209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='campaign_title',
            field=models.CharField(max_length=500),
        ),
    ]
