# Generated by Django 3.1.4 on 2021-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0009_auto_20210209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='campaign_title',
            field=models.CharField(max_length=255),
        ),
    ]
